server:
  port: 9000

zuul:
  routes:
    order:
      path: /zzshx/**
      serviceId: order
      strip-prefix: false


order:
  ribbon:
    listOfServers:
      http://49.233.85.147:10000,http://49.233.85.147:10001
    MaxAutoRetries: 1
    MaxAutoRetriesNextServer: 2
    ConnectTimeOut: 250
    OkToRetryOnAllOperation: true

logging:
  level:
    root: trace


