server:
  port: 9000

zuul:
  routes:
    order:
      path: /zzshx/**
      serviceId: order
      url: http://127.0.0.1:10000
      strip-prefix: false


order:
  service:
    url: http://127.0.0.1:10000
  ribbon:
    listOfServers:
      http://49.233.85.147:10000,http://49.233.85.147:10001
    MaxAutoRetries: 1
    MaxAutoRetriesNextServer: 2
    ConnectTimeOut: 250
    OkToRetryOnAllOperation: true

logging:
  level:
    root: trace


